// %import .grammars.exact_number.exact
// %import .inexact_number.inexact

file : expr*

expr : boolean
     | string
     //| symbol
     //| number
     //| image
     //| function_call

boolean : TRUE | FALSE

string : "\"" (ESCAPED_CHAR | UNESCAPED_CHAR)* "\""

// number : exact | inexact

TRUE : "#true"
FALSE : "#false"

UNESCAPED_CHAR : /[^\\"]/
ESCAPED_CHAR : /\\[abefnrtv"'\\]/
             | /\\[0-9]{1,3}/
             | /\\x[0-9a-fA-F]{1,2}/
             | /\\u[0-9a-fA-F]{1,4}/
             | /\\u[0-9a-fA-F]{4}\\u[0-9a-fA-F]{4}/
             | /\\U[0-9a-fA-F]{1,8}/
